version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: uat

      SERVER_PORT: 8080

      DATASOURCE_URL: jdbc:mysql://db:3306/pharmacy
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD: 1234

      SPRING_MAIL_USERNAME: tuantt3010@gmail.com
      SPRING_MAIL_PASSWORD: cmsh xcjm zpnm jnst

      JWT_SECRET: Jm/t4iRHPEvp1fFxY3ft0yRytsrRJrjctdLbRlRD+JjF9MBPcyEFOYZ0tqsLKOJe
      JWT_EXPIRATION: 3600
      JWT_RESET_PASSWORD_EXPIRATION: 600
      JWT_REFRESH_EXPIRATION: 86400

      DEFAULT_ADMIN_EMAIL: admin@gmail.com
      DEFAULT_ADMIN_PASSWORD: admin123

      FILE_UPLOAD_DIR: /app/uploads

      VNPAY_TMN_CODE: 6KSI353Z
      VNPAY_HASH_SECRET: 4SLLZP5HVM6ZS2VPQBSLJKM613W1I4CG
      VNPAY_URL: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      VNPAY_RETURN_URL: http://localhost:8080/api/v1/vnpay/return

      FRONTEND_PAYMENT_RETURN_URL: http://localhost:3001/payment
      FRONTEND_CMS_URL: http://localhost:3000/admin
      FRONTEND_USER_URL: http://localhost:3001
      BASE_URL: http://localhost:8080
    volumes:
      - app_uploads:/app/uploads

    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: pharmacy
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  app_uploads:
  db_data: