spring:
  jpa:
    hibernate:
      # This setting controls the schema generation strategy. Can change to 'create', 'create-drop', or 'validate' as needed.
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
  profiles:
    active: uat
  sql:
    init:
        # Executing any SQL scripts at startup. Can change to 'always' or 'embedded' as needed.
      mode: never
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: youremail@gmail.com
    password: yourAppPassword
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        default:
          encoding: UTF-8
jwt:
  secret: your_jwt_secret_key_here
  expiration: 3600
  refresh:
    expiration: 86400
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
account:
  default:
    email: admin@gmail.com
    password: admin123
file:
  upload:
    dir: D:/upload

