server:
  port: ${SERVER_PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:uat}
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

file:
  upload:
    dir: ${FILE_UPLOAD_DIR}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600}
  reset-password:
    expiration: ${JWT_RESET_PASSWORD_EXPIRATION:600}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION:86400}

default-admin:
  email: ${DEFAULT_ADMIN_EMAIL}
  password: ${DEFAULT_ADMIN_PASSWORD}

vnpay:
  tmn-code: ${VNPAY_TMN_CODE}
  hash-secret: ${VNPAY_HASH_SECRET}
  vnp-url: ${VNPAY_URL}
  return-url: ${VNPAY_RETURN_URL}

frontend:
  vnp-return: ${FRONTEND_PAYMENT_RETURN_URL}
  cms-url: ${FRONTEND_CMS_URL}
  user-url: ${FRONTEND_USER_URL}

app:
  base-url: ${APP_BASE_URL:http://localhost:8080}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

