spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
  profiles:
    active: uat
  sql:
    init:
      mode: never
jwt:
  secret: Jm/t4iRHPEvp1fFxY3ft0yRytsrRJrjctdLbRlRD+JjF9MBPcyEFOYZ0tqsLKOJe
  expiration: 3600
  refresh:
    expiration: 86400
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
account:
  default:
    email: admin@gmail.com
    password: admin123
