spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  profiles:
    active: uat
  mail:
    host: smtp.gmail.com
    port: 587
    username: datdnk3@gmail.com
    password: qfdr qvcl ilqn mvqa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  signerKey: +kNjFSE8cVRulovjPXzKK39I+6SqDrdHPoRmd5ShBx2ms4fIT9xIZd8balTZpyxT
app:
  base-url: "http://127.0.0.1:8000"
vnpay:
  payUrl: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  returnUrl: "http://localhost:8080/api/vnpay/vnpay_return"
  tmnCode: "TY24L0SC"
  secretKey: "OLLNHDCEMOEUUO6KJ12C1F9B9GMX4A3N"
  apiUrl: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"